name = "GFX"
uuid = "65bb6014-af4f-4359-bfe9-dc7ee7256e7a"
authors = ["wmkouw <wmkouw@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
ForneyLab = "9fc3f58a-c2cc-5bff-9419-6a294fefdca9"
